server:
  port: 8762

spring:
  application:
    name: service-hi
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/